### ISSUE TITLE
(BigNumber Error: new BigNumber() not a number: 0x)

### ISSUE THREAD

**Issue by ligi** [lexansoft/etherid.org#4]
I am getting the following error when searching for a domain:

```
Web3 Error!

Cannot connect to the Ethereum network. Please install and run an Ethereum client. 
(BigNumber Error: new BigNumber() not a number: 0x)
```

the node is running - I see other things like my balance and get a different ( expected ) error than when the node is not running:

```
Web3 Error!

Cannot connect to the Ethereum network. Please install and run an Ethereum client. 
(Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545, is it running?)
```

**Comment by lexansoft** [comment]
FIxed. The problem was with searching for "0x". It was recognized as a hex number, but it has no actual digits.  The fix now treats 0x as an ASCII string with hex value  0x3078

Note. The current mist version has a caching problem, so even if you refresh the webpage, it might still use the old one. Hopefully it will be fixed by mist team soon.

**Comment by ligi** [comment]
I am still experiencing the problem - not using mist - just a browser -
there should be no caching problem here

**Comment by lexansoft** [comment]
What browser?

**Comment by ligi** [comment]
tried it with cromium before.

But as you asked this I tried it with FireFox -> works , then tested
with chromium again and now also the error does not appea anymore -
perhaps the change was just not rolled out at this point in time?

**Comment by lexansoft** [comment]
Great.

Alexandre Naverniouk

**Comment by Velofisch** [comment]
Hi,
I keep getting the same error when I try to write a transaction.
When calling the typed transactions from the JavaScript library - what is the correct type conversion? Should I rather adhere to the types of the methods of the contract or should I always try to convert into a hex string (with web3.fromAscII()) - as it had been the case before?

The error message is: "Error: new BigNumber() not a number: b".
The stack is:
raise() in web3.js:14248
another/parseNumeric</<() in web3.js:14236
BigNumber() in web3.js:13264
BigNumber() in web3.js:13274
require<[20]</toBigNumber() in web3.js:2235
require<[20]</toTwosComplement() in web3.js:2246
require<[9]</formatInputInt() in web3.js:949
require<[14]</SolidityType.prototype.encode() in web3.js:1597
require<[7]</SolidityCoder.prototype.encodeParams/encodeds<() in web3.js:706
map() in self-hosted:235
require<[7]</SolidityCoder.prototype.encodeParams() in web3.js:705
require<[31]</SolidityFunction.prototype.toPayload() in web3.js:3909
require<[31]</SolidityFunction.prototype.sendTransaction() in web3.js:3970
require<[31]</SolidityFunction.prototype.execute() in web3.js:4059
pledge() in pledge.html:129
onclick() in  pledge.html:1

pledge.html is my file where I call the SolidityFunction

Thank you very much for your help!

**Comment by cloxy** [comment]
I am getting the same error on all browsers. Please help.

**Comment by lexansoft** [comment]
1. You can pass BigNumber value.
2. You can pass a hexadecimal string in format: 0x######. But, note that if
   you pass just 0x with no digits after the hex converter will fail.
3. The best way to call the EtherId contract if through the etherid-js
   module. You can check the test html page there.

https://github.com/lexansoft/etherid-js

Alexandre Naverniouk
